version: 2
updates:
  # Root and workspace npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    versioning-strategy: 'increase'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(ci)'
    labels:
      - 'dependencies'
      - 'ci'
