import type {
  ApiEndpoint,
  ExecutionLog,
  TestCase,
  Variable,
  WorkflowMeta,
  WorkflowStep,
} from './types';

export const initialSteps: WorkflowStep[] = [
  {
    id: 'create-user',
    name: '创建用户',
    method: 'POST',
    path: '/api/users',
    icon: 'user',
    tone: 'brown',
    variableName: 'userId',
    variablePath: '$.data.userId',
    expectedStatus: 201,
    assertion: '$.code = 0',
    sourceEndpointId: 'e1',
  },
  {
    id: 'login',
    name: '登录',
    method: 'POST',
    path: '/api/auth/login',
    icon: 'lock',
    tone: 'amber',
    variableName: 'accessToken',
    variablePath: '$.data.accessToken',
    expectedStatus: 200,
    assertion: '$.code = 0',
    sourceEndpointId: 'e2',
  },
  {
    id: 'create-order',
    name: '创建订单',
    method: 'POST',
    path: '/api/orders',
    icon: 'cart',
    tone: 'green',
    variableName: 'orderId',
    variablePath: '$.data.orderId',
    expectedStatus: 201,
    assertion: '$.code = 0',
    sourceEndpointId: 'e3',
  },
  {
    id: 'pay',
    name: '支付',
    method: 'POST',
    path: '/api/payments',
    icon: 'card',
    tone: 'brick',
    variableName: 'paymentId',
    variablePath: '$.data.paymentId',
    expectedStatus: 200,
    assertion: '$.code = 0',
    sourceEndpointId: 'e4',
  },
  {
    id: 'verify',
    name: '验证状态',
    method: 'GET',
    path: '/api/orders/{orderId}',
    icon: 'verify',
    tone: 'violet',
    variableName: 'status',
    variablePath: '$.data.status',
    expectedStatus: 200,
    assertion: '$.data.status = 已支付',
    sourceEndpointId: 'e5',
  },
];

export const endpoints: ApiEndpoint[] = [
  { id: 'e1', method: 'POST', path: '/api/users', summary: '创建用户', coverage: 100, cases: 8 },
  {
    id: 'e2',
    method: 'POST',
    path: '/api/auth/login',
    summary: '用户登录',
    coverage: 100,
    cases: 6,
  },
  { id: 'e3', method: 'POST', path: '/api/orders', summary: '创建订单', coverage: 92, cases: 12 },
  { id: 'e4', method: 'POST', path: '/api/payments', summary: '支付订单', coverage: 76, cases: 9 },
  {
    id: 'e5',
    method: 'GET',
    path: '/api/orders/{orderId}',
    summary: '查询订单',
    coverage: 100,
    cases: 7,
  },
  {
    id: 'e6',
    method: 'DELETE',
    path: '/api/orders/{orderId}',
    summary: '取消订单',
    coverage: 42,
    cases: 3,
  },
];

export const initialCases: TestCase[] = [
  {
    id: 'c1',
    name: '创建用户 · 正常请求',
    endpoint: 'POST /api/users',
    source: 'OpenAPI',
    status: '已发布',
    lastRun: '3 分钟前',
  },
  {
    id: 'c2',
    name: '创建订单 · 缺少 userId',
    endpoint: 'POST /api/orders',
    source: 'OpenAPI',
    status: '已发布',
    lastRun: '8 分钟前',
  },
  {
    id: 'c3',
    name: '支付订单 · 金额边界',
    endpoint: 'POST /api/payments',
    source: 'AI Agent',
    status: '待审核',
    lastRun: '尚未运行',
  },
  {
    id: 'c4',
    name: '查询订单 · 越权访问',
    endpoint: 'GET /api/orders/{id}',
    source: 'AI Agent',
    status: '待审核',
    lastRun: '尚未运行',
  },
];

export const initialLogs: ExecutionLog[] = initialSteps.map((step) => ({
  id: `log-${step.id}`,
  stepId: step.id,
  name: step.name,
  method: step.method,
  path: step.path,
  status: 'queued',
}));

// ─── All 8 Business Processes (from CONTEXT.md) ─────────────────

export const workflows: WorkflowMeta[] = [
  {
    id: 'wf-bp01',
    bpId: 'BP-01',
    name: '用户注册与认证',
    description: '注册新用户并完成登录认证，验证身份令牌的有效性。',
    stepCount: 3,
    variableChain: ['userId', 'accessToken'],
    sideEffect: 'cleanable-write',
    category: 'normal',
    status: 'healthy',
    lastRun: '10 分钟前',
    tags: ['认证', '用户', 'Happy Path'],
  },
  {
    id: 'wf-bp02',
    bpId: 'BP-02',
    name: '创建订单并支付',
    description: '用户登录后创建订单并完成支付，验证订单状态流转。',
    stepCount: 5,
    variableChain: ['accessToken', 'orderId', 'paymentId'],
    sideEffect: 'irreversible',
    category: 'normal',
    status: 'warning',
    lastRun: '8 分钟前',
    tags: ['订单', '支付', '核心流程'],
  },
  {
    id: 'wf-bp03',
    bpId: 'BP-03',
    name: '订单生命周期管理',
    description: '创建订单、查询详情、取消订单的完整生命周期。',
    stepCount: 3,
    variableChain: ['orderId', 'status'],
    sideEffect: 'cleanable-write',
    category: 'normal',
    status: 'healthy',
    lastRun: '12 分钟前',
    tags: ['订单', '生命周期', 'CRUD'],
  },
  {
    id: 'wf-bp04',
    bpId: 'BP-04',
    name: '用户信息查询与更新',
    description: '登录后查询当前用户信息，验证只读接口的权限控制。',
    stepCount: 2,
    variableChain: ['accessToken', 'userId'],
    sideEffect: 'readonly',
    category: 'normal',
    status: 'healthy',
    lastRun: '15 分钟前',
    tags: ['用户', '查询', '只读'],
  },
  {
    id: 'wf-bp05',
    bpId: 'BP-05',
    name: '支付状态轮询',
    description: '发起支付后轮询订单状态直至支付完成，验证异步回调模式。',
    stepCount: 2,
    variableChain: ['paymentId', 'orderId', 'status'],
    sideEffect: 'irreversible',
    category: 'normal',
    status: 'draft',
    tags: ['支付', '轮询', '异步'],
  },
  {
    id: 'wf-bp06',
    bpId: 'BP-06',
    name: '异常路径：重复支付保护',
    description: '对同一订单重复发起支付，验证幂等性保护和错误响应。',
    stepCount: 2,
    variableChain: ['orderId', 'status'],
    sideEffect: 'irreversible',
    category: 'error-path',
    status: 'healthy',
    lastRun: '20 分钟前',
    tags: ['支付', '幂等', '异常'],
  },
  {
    id: 'wf-bp07',
    bpId: 'BP-07',
    name: '异常路径：认证失败处理',
    description: '使用错误凭证登录，验证 401 响应和错误信息格式。',
    stepCount: 1,
    variableChain: [],
    sideEffect: 'readonly',
    category: 'error-path',
    status: 'healthy',
    lastRun: '25 分钟前',
    tags: ['认证', '401', '异常'],
  },
  {
    id: 'wf-bp08',
    bpId: 'BP-08',
    name: '异常路径：参数校验失败',
    description: '发送缺少必填字段的请求，验证 400 响应和字段级错误。',
    stepCount: 1,
    variableChain: [],
    sideEffect: 'readonly',
    category: 'error-path',
    status: 'healthy',
    lastRun: '30 分钟前',
    tags: ['校验', '400', '异常'],
  },
];

/** Step definitions for each business process. */
export const workflowStepsMap: Record<string, WorkflowStep[]> = {
  'wf-bp01': [
    {
      id: 'bp01-create-user',
      name: '创建用户',
      method: 'POST',
      path: '/api/users',
      icon: 'user',
      tone: 'brown',
      variableName: 'userId',
      variablePath: '$.data.userId',
      expectedStatus: 201,
      assertion: '$.code = 0',
      sourceEndpointId: 'e1',
    },
    {
      id: 'bp01-login',
      name: '登录',
      method: 'POST',
      path: '/api/auth/login',
      icon: 'lock',
      tone: 'amber',
      variableName: 'accessToken',
      variablePath: '$.data.accessToken',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e2',
    },
    {
      id: 'bp01-me',
      name: '验证身份',
      method: 'GET',
      path: '/api/auth/me',
      icon: 'verify',
      tone: 'violet',
      variableName: 'userProfile',
      variablePath: '$.data.username',
      expectedStatus: 200,
      assertion: '$.data.username != null',
    },
  ],
  'wf-bp02': [
    {
      id: 'create-user',
      name: '创建用户',
      method: 'POST',
      path: '/api/users',
      icon: 'user',
      tone: 'brown',
      variableName: 'userId',
      variablePath: '$.data.userId',
      expectedStatus: 201,
      assertion: '$.code = 0',
      sourceEndpointId: 'e1',
    },
    {
      id: 'login',
      name: '登录',
      method: 'POST',
      path: '/api/auth/login',
      icon: 'lock',
      tone: 'amber',
      variableName: 'accessToken',
      variablePath: '$.data.accessToken',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e2',
    },
    {
      id: 'create-order',
      name: '创建订单',
      method: 'POST',
      path: '/api/orders',
      icon: 'cart',
      tone: 'green',
      variableName: 'orderId',
      variablePath: '$.data.orderId',
      expectedStatus: 201,
      assertion: '$.code = 0',
      sourceEndpointId: 'e3',
    },
    {
      id: 'pay',
      name: '支付',
      method: 'POST',
      path: '/api/payments',
      icon: 'card',
      tone: 'brick',
      variableName: 'paymentId',
      variablePath: '$.data.paymentId',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e4',
    },
    {
      id: 'verify',
      name: '验证状态',
      method: 'GET',
      path: '/api/orders/{orderId}',
      icon: 'verify',
      tone: 'violet',
      variableName: 'status',
      variablePath: '$.data.status',
      expectedStatus: 200,
      assertion: '$.data.status = 已支付',
      sourceEndpointId: 'e5',
    },
  ],
  'wf-bp03': [
    {
      id: 'bp03-create',
      name: '创建订单',
      method: 'POST',
      path: '/api/orders',
      icon: 'cart',
      tone: 'green',
      variableName: 'orderId',
      variablePath: '$.data.orderId',
      expectedStatus: 201,
      assertion: '$.code = 0',
      sourceEndpointId: 'e3',
    },
    {
      id: 'bp03-query',
      name: '查询订单',
      method: 'GET',
      path: '/api/orders/{orderId}',
      icon: 'verify',
      tone: 'violet',
      variableName: 'status',
      variablePath: '$.data.status',
      expectedStatus: 200,
      assertion: '$.data.orderId != null',
      sourceEndpointId: 'e5',
    },
    {
      id: 'bp03-delete',
      name: '取消订单',
      method: 'DELETE',
      path: '/api/orders/{orderId}',
      icon: 'card',
      tone: 'brick',
      variableName: 'result',
      variablePath: '$.message',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e6',
    },
  ],
  'wf-bp04': [
    {
      id: 'bp04-login',
      name: '登录',
      method: 'POST',
      path: '/api/auth/login',
      icon: 'lock',
      tone: 'amber',
      variableName: 'accessToken',
      variablePath: '$.data.accessToken',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e2',
    },
    {
      id: 'bp04-query',
      name: '查询用户',
      method: 'GET',
      path: '/api/users/{userId}',
      icon: 'user',
      tone: 'brown',
      variableName: 'userInfo',
      variablePath: '$.data',
      expectedStatus: 200,
      assertion: '$.data.username != null',
    },
  ],
  'wf-bp05': [
    {
      id: 'bp05-pay',
      name: '发起支付',
      method: 'POST',
      path: '/api/payments',
      icon: 'card',
      tone: 'brick',
      variableName: 'paymentId',
      variablePath: '$.data.paymentId',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e4',
    },
    {
      id: 'bp05-poll',
      name: '轮询状态',
      method: 'GET',
      path: '/api/orders/{orderId}',
      icon: 'verify',
      tone: 'amber',
      variableName: 'status',
      variablePath: '$.data.status',
      expectedStatus: 200,
      assertion: '$.data.status = 已支付',
      sourceEndpointId: 'e5',
    },
  ],
  'wf-bp06': [
    {
      id: 'bp06-first',
      name: '首次支付',
      method: 'POST',
      path: '/api/payments',
      icon: 'card',
      tone: 'brick',
      variableName: 'paymentId1',
      variablePath: '$.data.paymentId',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e4',
    },
    {
      id: 'bp06-dup',
      name: '重复支付',
      method: 'POST',
      path: '/api/payments',
      icon: 'card',
      tone: 'violet',
      variableName: 'errorCode',
      variablePath: '$.code',
      expectedStatus: 409,
      assertion: '$.code != 0',
      sourceEndpointId: 'e4',
    },
  ],
  'wf-bp07': [
    {
      id: 'bp07-bad-login',
      name: '错误凭证登录',
      method: 'POST',
      path: '/api/auth/login',
      icon: 'lock',
      tone: 'brick',
      variableName: 'errorCode',
      variablePath: '$.code',
      expectedStatus: 401,
      assertion: '$.code != 0',
      sourceEndpointId: 'e2',
    },
  ],
  'wf-bp08': [
    {
      id: 'bp08-bad-request',
      name: '缺失字段请求',
      method: 'POST',
      path: '/api/users',
      icon: 'user',
      tone: 'brick',
      variableName: 'fieldProblems',
      variablePath: '$.errors',
      expectedStatus: 400,
      assertion: '$.code != 0',
      sourceEndpointId: 'e1',
    },
  ],
};

/** Generate execution logs for a given workflow's steps. */
export function makeLogs(steps: WorkflowStep[]): ExecutionLog[] {
  return steps.map((step) => ({
    id: `log-${step.id}`,
    stepId: step.id,
    name: step.name,
    method: step.method,
    path: step.path,
    status: 'queued',
  }));
}

export const responseFixture = `{
  "code": 0,
  "data": {
    "orderId": "123456",
    "status": "待支付",
    "amount": 199.00,
    "createTime": "2026-06-21 10:30:58"
  },
  "message": "success"
}`;

// ─── Variables ─────────────────────────────────────────────────

export const initialVariables: Variable[] = [
  {
    id: 'var-baseUrl',
    name: 'baseUrl',
    value: 'https://test.api.sketch.dev',
    type: 'plain',
    scope: 'environment',
    sensitive: false,
    description: '测试环境的基础 URL，所有接口请求的前缀。',
    updatedAt: '2026-06-20 14:30',
    updatedBy: 'QA_team',
    usedIn: ['BP-01', 'BP-02', 'BP-03', 'BP-04'],
  },
  {
    id: 'var-accessToken',
    name: 'accessToken',
    value: 'sk_test_A7s9Kx21Ym8pQ3rL5nV',
    type: 'secret',
    scope: 'step',
    sensitive: true,
    description: '登录后提取的访问令牌，用于后续请求的 Authorization 头。',
    updatedAt: '2026-06-17 09:15',
    updatedBy: 'QA_team',
    usedIn: ['BP-02', 'BP-04'],
  },
  {
    id: 'var-apiTimeout',
    name: 'apiTimeout',
    value: '30000',
    type: 'plain',
    scope: 'workflow',
    sensitive: false,
    description: 'API 请求超时时间（毫秒），默认 30 秒。',
    updatedAt: '2026-06-19 16:45',
    updatedBy: 'QA_team',
    usedIn: ['BP-01', 'BP-02', 'BP-03', 'BP-04', 'BP-05', 'BP-06'],
  },
  {
    id: 'var-maxRetries',
    name: 'maxRetries',
    value: '3',
    type: 'plain',
    scope: 'workflow',
    sensitive: false,
    description: '失败步骤的最大重试次数，超出后标记流程失败。',
    updatedAt: '2026-06-16 11:00',
    updatedBy: 'QA_team',
    usedIn: ['BP-02', 'BP-05', 'BP-06'],
  },
  {
    id: 'var-stagingBaseUrl',
    name: 'stagingBaseUrl',
    value: 'https://staging.api.sketch.dev',
    type: 'plain',
    scope: 'environment',
    sensitive: false,
    description: '预发布环境的基础 URL，用于上线前验证。',
    updatedAt: '2026-06-15 08:20',
    updatedBy: 'QA_team',
    usedIn: [],
  },
  {
    id: 'var-dbReadOnly',
    name: 'dbReadOnlyToken',
    value: 'sk_ro_3fA8zL2kQ9xM6wV',
    type: 'secret',
    scope: 'environment',
    sensitive: true,
    description: '生产只读环境的数据库访问令牌，仅限查询操作。',
    updatedAt: '2026-06-14 13:30',
    updatedBy: 'QA_team',
    usedIn: ['BP-04'],
  },
  {
    id: 'var-userDataset',
    name: 'testUsers',
    value:
      '{"admin":{"username":"admin","password":"***"},"guest":{"username":"guest","password":"***"}}',
    type: 'dataset',
    scope: 'environment',
    sensitive: true,
    description: '测试用户数据集，包含不同角色的登录凭证。',
    updatedAt: '2026-06-13 10:00',
    updatedBy: 'QA_team',
    usedIn: ['BP-01', 'BP-07'],
  },
  {
    id: 'var-pollInterval',
    name: 'pollIntervalMs',
    value: '2000',
    type: 'plain',
    scope: 'workflow',
    sensitive: false,
    description: '轮询间隔（毫秒），用于支付状态等异步场景。',
    updatedAt: '2026-06-18 15:20',
    updatedBy: 'QA_team',
    usedIn: ['BP-05'],
  },
];
