import type {
  ApiEndpoint,
  Environment,
  ExecutionLog,
  RunMeta,
  TestCase,
  TestPlan,
  Variable,
  WorkflowMeta,
  WorkflowStep,
} from './types';

export const initialSteps: WorkflowStep[] = [
  {
    id: 'create-user',
    name: '创建用户',
    method: 'POST',
    path: '/api/users',
    icon: 'user',
    tone: 'brown',
    variableName: 'userId',
    variablePath: '$.data.userId',
    expectedStatus: 201,
    assertion: '$.code = 0',
    sourceEndpointId: 'e1',
  },
  {
    id: 'login',
    name: '登录',
    method: 'POST',
    path: '/api/auth/login',
    icon: 'lock',
    tone: 'amber',
    variableName: 'accessToken',
    variablePath: '$.data.accessToken',
    expectedStatus: 200,
    assertion: '$.code = 0',
    sourceEndpointId: 'e2',
  },
  {
    id: 'create-order',
    name: '创建订单',
    method: 'POST',
    path: '/api/orders',
    icon: 'cart',
    tone: 'green',
    variableName: 'orderId',
    variablePath: '$.data.orderId',
    expectedStatus: 201,
    assertion: '$.code = 0',
    sourceEndpointId: 'e3',
  },
  {
    id: 'pay',
    name: '支付',
    method: 'POST',
    path: '/api/payments',
    icon: 'card',
    tone: 'brick',
    variableName: 'paymentId',
    variablePath: '$.data.paymentId',
    expectedStatus: 200,
    assertion: '$.code = 0',
    sourceEndpointId: 'e4',
  },
  {
    id: 'verify',
    name: '验证状态',
    method: 'GET',
    path: '/api/orders/{orderId}',
    icon: 'verify',
    tone: 'violet',
    variableName: 'status',
    variablePath: '$.data.status',
    expectedStatus: 200,
    assertion: '$.data.status = 已支付',
    sourceEndpointId: 'e5',
  },
];

export const endpoints: ApiEndpoint[] = [
  { id: 'e1', method: 'POST', path: '/api/users', summary: '创建用户', coverage: 100, cases: 8 },
  {
    id: 'e2',
    method: 'POST',
    path: '/api/auth/login',
    summary: '用户登录',
    coverage: 100,
    cases: 6,
  },
  { id: 'e3', method: 'POST', path: '/api/orders', summary: '创建订单', coverage: 92, cases: 12 },
  { id: 'e4', method: 'POST', path: '/api/payments', summary: '支付订单', coverage: 76, cases: 9 },
  {
    id: 'e5',
    method: 'GET',
    path: '/api/orders/{orderId}',
    summary: '查询订单',
    coverage: 100,
    cases: 7,
  },
  {
    id: 'e6',
    method: 'DELETE',
    path: '/api/orders/{orderId}',
    summary: '取消订单',
    coverage: 42,
    cases: 3,
  },
];

export const initialCases: TestCase[] = [
  {
    id: 'c1',
    name: '创建用户 · 正常请求',
    endpoint: 'POST /api/users',
    source: 'OpenAPI',
    status: '已发布',
    lastRun: '3 分钟前',
  },
  {
    id: 'c2',
    name: '创建订单 · 缺少 userId',
    endpoint: 'POST /api/orders',
    source: 'OpenAPI',
    status: '已发布',
    lastRun: '8 分钟前',
  },
  {
    id: 'c3',
    name: '支付订单 · 金额边界',
    endpoint: 'POST /api/payments',
    source: 'AI Agent',
    status: '待审核',
    lastRun: '尚未运行',
  },
  {
    id: 'c4',
    name: '查询订单 · 越权访问',
    endpoint: 'GET /api/orders/{id}',
    source: 'AI Agent',
    status: '待审核',
    lastRun: '尚未运行',
  },
];

export const initialLogs: ExecutionLog[] = initialSteps.map((step) => ({
  id: `log-${step.id}`,
  stepId: step.id,
  name: step.name,
  method: step.method,
  path: step.path,
  status: 'queued',
}));

// ─── All 8 Business Processes (from CONTEXT.md) ─────────────────

export const workflows: WorkflowMeta[] = [
  {
    id: 'wf-bp01',
    bpId: 'BP-01',
    name: '用户注册与认证',
    description: '注册新用户并完成登录认证，验证身份令牌的有效性。',
    stepCount: 3,
    variableChain: ['userId', 'accessToken'],
    sideEffect: 'cleanable-write',
    category: 'normal',
    status: 'healthy',
    lastRun: '10 分钟前',
    tags: ['认证', '用户', 'Happy Path'],
  },
  {
    id: 'wf-bp02',
    bpId: 'BP-02',
    name: '创建订单并支付',
    description: '用户登录后创建订单并完成支付，验证订单状态流转。',
    stepCount: 5,
    variableChain: ['accessToken', 'orderId', 'paymentId'],
    sideEffect: 'irreversible',
    category: 'normal',
    status: 'warning',
    lastRun: '8 分钟前',
    tags: ['订单', '支付', '核心流程'],
  },
  {
    id: 'wf-bp03',
    bpId: 'BP-03',
    name: '订单生命周期管理',
    description: '创建订单、查询详情、取消订单的完整生命周期。',
    stepCount: 3,
    variableChain: ['orderId', 'status'],
    sideEffect: 'cleanable-write',
    category: 'normal',
    status: 'healthy',
    lastRun: '12 分钟前',
    tags: ['订单', '生命周期', 'CRUD'],
  },
  {
    id: 'wf-bp04',
    bpId: 'BP-04',
    name: '用户信息查询与更新',
    description: '登录后查询当前用户信息，验证只读接口的权限控制。',
    stepCount: 2,
    variableChain: ['accessToken', 'userId'],
    sideEffect: 'readonly',
    category: 'normal',
    status: 'healthy',
    lastRun: '15 分钟前',
    tags: ['用户', '查询', '只读'],
  },
  {
    id: 'wf-bp05',
    bpId: 'BP-05',
    name: '支付状态轮询',
    description: '发起支付后轮询订单状态直至支付完成，验证异步回调模式。',
    stepCount: 2,
    variableChain: ['paymentId', 'orderId', 'status'],
    sideEffect: 'irreversible',
    category: 'normal',
    status: 'draft',
    tags: ['支付', '轮询', '异步'],
  },
  {
    id: 'wf-bp06',
    bpId: 'BP-06',
    name: '异常路径：重复支付保护',
    description: '对同一订单重复发起支付，验证幂等性保护和错误响应。',
    stepCount: 2,
    variableChain: ['orderId', 'status'],
    sideEffect: 'irreversible',
    category: 'error-path',
    status: 'healthy',
    lastRun: '20 分钟前',
    tags: ['支付', '幂等', '异常'],
  },
  {
    id: 'wf-bp07',
    bpId: 'BP-07',
    name: '异常路径：认证失败处理',
    description: '使用错误凭证登录，验证 401 响应和错误信息格式。',
    stepCount: 1,
    variableChain: [],
    sideEffect: 'readonly',
    category: 'error-path',
    status: 'healthy',
    lastRun: '25 分钟前',
    tags: ['认证', '401', '异常'],
  },
  {
    id: 'wf-bp08',
    bpId: 'BP-08',
    name: '异常路径：参数校验失败',
    description: '发送缺少必填字段的请求，验证 400 响应和字段级错误。',
    stepCount: 1,
    variableChain: [],
    sideEffect: 'readonly',
    category: 'error-path',
    status: 'healthy',
    lastRun: '30 分钟前',
    tags: ['校验', '400', '异常'],
  },
];

/** Step definitions for each business process. */
export const workflowStepsMap: Record<string, WorkflowStep[]> = {
  'wf-bp01': [
    {
      id: 'bp01-create-user',
      name: '创建用户',
      method: 'POST',
      path: '/api/users',
      icon: 'user',
      tone: 'brown',
      variableName: 'userId',
      variablePath: '$.data.userId',
      expectedStatus: 201,
      assertion: '$.code = 0',
      sourceEndpointId: 'e1',
    },
    {
      id: 'bp01-login',
      name: '登录',
      method: 'POST',
      path: '/api/auth/login',
      icon: 'lock',
      tone: 'amber',
      variableName: 'accessToken',
      variablePath: '$.data.accessToken',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e2',
    },
    {
      id: 'bp01-me',
      name: '验证身份',
      method: 'GET',
      path: '/api/auth/me',
      icon: 'verify',
      tone: 'violet',
      variableName: 'userProfile',
      variablePath: '$.data.username',
      expectedStatus: 200,
      assertion: '$.data.username != null',
    },
  ],
  'wf-bp02': [
    {
      id: 'create-user',
      name: '创建用户',
      method: 'POST',
      path: '/api/users',
      icon: 'user',
      tone: 'brown',
      variableName: 'userId',
      variablePath: '$.data.userId',
      expectedStatus: 201,
      assertion: '$.code = 0',
      sourceEndpointId: 'e1',
    },
    {
      id: 'login',
      name: '登录',
      method: 'POST',
      path: '/api/auth/login',
      icon: 'lock',
      tone: 'amber',
      variableName: 'accessToken',
      variablePath: '$.data.accessToken',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e2',
    },
    {
      id: 'create-order',
      name: '创建订单',
      method: 'POST',
      path: '/api/orders',
      icon: 'cart',
      tone: 'green',
      variableName: 'orderId',
      variablePath: '$.data.orderId',
      expectedStatus: 201,
      assertion: '$.code = 0',
      sourceEndpointId: 'e3',
    },
    {
      id: 'pay',
      name: '支付',
      method: 'POST',
      path: '/api/payments',
      icon: 'card',
      tone: 'brick',
      variableName: 'paymentId',
      variablePath: '$.data.paymentId',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e4',
    },
    {
      id: 'verify',
      name: '验证状态',
      method: 'GET',
      path: '/api/orders/{orderId}',
      icon: 'verify',
      tone: 'violet',
      variableName: 'status',
      variablePath: '$.data.status',
      expectedStatus: 200,
      assertion: '$.data.status = 已支付',
      sourceEndpointId: 'e5',
    },
  ],
  'wf-bp03': [
    {
      id: 'bp03-create',
      name: '创建订单',
      method: 'POST',
      path: '/api/orders',
      icon: 'cart',
      tone: 'green',
      variableName: 'orderId',
      variablePath: '$.data.orderId',
      expectedStatus: 201,
      assertion: '$.code = 0',
      sourceEndpointId: 'e3',
    },
    {
      id: 'bp03-query',
      name: '查询订单',
      method: 'GET',
      path: '/api/orders/{orderId}',
      icon: 'verify',
      tone: 'violet',
      variableName: 'status',
      variablePath: '$.data.status',
      expectedStatus: 200,
      assertion: '$.data.orderId != null',
      sourceEndpointId: 'e5',
    },
    {
      id: 'bp03-delete',
      name: '取消订单',
      method: 'DELETE',
      path: '/api/orders/{orderId}',
      icon: 'card',
      tone: 'brick',
      variableName: 'result',
      variablePath: '$.message',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e6',
    },
  ],
  'wf-bp04': [
    {
      id: 'bp04-login',
      name: '登录',
      method: 'POST',
      path: '/api/auth/login',
      icon: 'lock',
      tone: 'amber',
      variableName: 'accessToken',
      variablePath: '$.data.accessToken',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e2',
    },
    {
      id: 'bp04-query',
      name: '查询用户',
      method: 'GET',
      path: '/api/users/{userId}',
      icon: 'user',
      tone: 'brown',
      variableName: 'userInfo',
      variablePath: '$.data',
      expectedStatus: 200,
      assertion: '$.data.username != null',
    },
  ],
  'wf-bp05': [
    {
      id: 'bp05-pay',
      name: '发起支付',
      method: 'POST',
      path: '/api/payments',
      icon: 'card',
      tone: 'brick',
      variableName: 'paymentId',
      variablePath: '$.data.paymentId',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e4',
    },
    {
      id: 'bp05-poll',
      name: '轮询状态',
      method: 'GET',
      path: '/api/orders/{orderId}',
      icon: 'verify',
      tone: 'amber',
      variableName: 'status',
      variablePath: '$.data.status',
      expectedStatus: 200,
      assertion: '$.data.status = 已支付',
      sourceEndpointId: 'e5',
    },
  ],
  'wf-bp06': [
    {
      id: 'bp06-first',
      name: '首次支付',
      method: 'POST',
      path: '/api/payments',
      icon: 'card',
      tone: 'brick',
      variableName: 'paymentId1',
      variablePath: '$.data.paymentId',
      expectedStatus: 200,
      assertion: '$.code = 0',
      sourceEndpointId: 'e4',
    },
    {
      id: 'bp06-dup',
      name: '重复支付',
      method: 'POST',
      path: '/api/payments',
      icon: 'card',
      tone: 'violet',
      variableName: 'errorCode',
      variablePath: '$.code',
      expectedStatus: 409,
      assertion: '$.code != 0',
      sourceEndpointId: 'e4',
    },
  ],
  'wf-bp07': [
    {
      id: 'bp07-bad-login',
      name: '错误凭证登录',
      method: 'POST',
      path: '/api/auth/login',
      icon: 'lock',
      tone: 'brick',
      variableName: 'errorCode',
      variablePath: '$.code',
      expectedStatus: 401,
      assertion: '$.code != 0',
      sourceEndpointId: 'e2',
    },
  ],
  'wf-bp08': [
    {
      id: 'bp08-bad-request',
      name: '缺失字段请求',
      method: 'POST',
      path: '/api/users',
      icon: 'user',
      tone: 'brick',
      variableName: 'fieldProblems',
      variablePath: '$.errors',
      expectedStatus: 400,
      assertion: '$.code != 0',
      sourceEndpointId: 'e1',
    },
  ],
};

/** Generate execution logs for a given workflow's steps. */
export function makeLogs(steps: WorkflowStep[]): ExecutionLog[] {
  return steps.map((step) => ({
    id: `log-${step.id}`,
    stepId: step.id,
    name: step.name,
    method: step.method,
    path: step.path,
    status: 'queued',
  }));
}

export const responseFixture = `{
  "code": 0,
  "data": {
    "orderId": "123456",
    "status": "待支付",
    "amount": 199.00,
    "createTime": "2026-06-21 10:30:58"
  },
  "message": "success"
}`;

// ─── Environments ───────────────────────────────────────────────

export const initialEnvironments: Environment[] = [
  {
    id: 'env-test',
    name: '测试环境',
    description: '本地和 CI 使用的集成测试环境，所有服务均可读写。',
    tags: ['test', 'integration'],
    isProduction: false,
    updatedAt: '2026-06-21 09:00',
    updatedBy: 'QA_team',
  },
  {
    id: 'env-staging',
    name: '预发布环境',
    description: '上线前最终验证环境，数据接近生产但不影响真实用户。',
    tags: ['staging', 'pre-release'],
    isProduction: false,
    updatedAt: '2026-06-21 14:00',
    updatedBy: 'QA_team',
  },
  {
    id: 'env-prod',
    name: '生产只读',
    description: '生产环境只读访问，禁止任何写操作和破坏性测试。',
    tags: ['production', 'read-only'],
    isProduction: true,
    updatedAt: '2026-06-20 16:30',
    updatedBy: 'QA_team',
  },
];

// ─── Variables ─────────────────────────────────────────────────

export const initialVariables: Variable[] = [
  {
    id: 'var-userService',
    name: 'userService',
    defaultValue: 'http://localhost:8080',
    overrides: {
      'env-test': 'https://user.test.api.sketch.dev',
      'env-staging': 'https://user.staging.api.sketch.dev',
      'env-prod': 'https://user.api.sketch.dev',
    },
    type: 'plain',
    scope: 'environment',
    sensitive: false,
    description: '用户服务的基础 URL，提供注册、登录、用户信息等接口。',
    updatedAt: '2026-06-21 10:30',
    updatedBy: 'QA_team',
    usedIn: ['BP-01', 'BP-02', 'BP-03', 'BP-07'],
  },
  {
    id: 'var-paymentService',
    name: 'paymentService',
    defaultValue: 'http://localhost:8081',
    overrides: {
      'env-test': 'https://pay.test.api.sketch.dev',
      'env-staging': 'https://pay.staging.api.sketch.dev',
      'env-prod': 'https://pay.api.sketch.dev',
    },
    type: 'plain',
    scope: 'environment',
    sensitive: false,
    description: '支付服务的基础 URL，提供订单支付、退款等接口。',
    updatedAt: '2026-06-21 10:35',
    updatedBy: 'QA_team',
    usedIn: ['BP-04', 'BP-05', 'BP-06'],
  },
  {
    id: 'var-notifyService',
    name: 'notifyService',
    defaultValue: 'http://localhost:8082',
    overrides: {
      'env-test': 'https://notify.test.api.sketch.dev',
      'env-staging': 'https://notify.staging.api.sketch.dev',
      'env-prod': 'https://notify.api.sketch.dev',
    },
    type: 'plain',
    scope: 'environment',
    sensitive: false,
    description: '通知服务的基础 URL，提供短信、邮件、站内信等推送接口。',
    updatedAt: '2026-06-21 10:40',
    updatedBy: 'QA_team',
    usedIn: ['BP-05'],
  },
  {
    id: 'var-accessToken',
    name: 'accessToken',
    defaultValue: 'sk_test_A7s9Kx21Ym8pQ3rL5nV',
    overrides: {
      'env-test': 'sk_test_A7s9Kx21Ym8pQ3rL5nV',
      'env-staging': 'sk_staging_B8t0Ly32Zn9qR4sM6oW',
      'env-prod': 'sk_prod_C9u1Mz43Ao0rS5tN7pX',
    },
    type: 'secret',
    scope: 'step',
    sensitive: true,
    description: '登录后提取的访问令牌，用于后续请求的 Authorization 头。',
    updatedAt: '2026-06-17 09:15',
    updatedBy: 'QA_team',
    usedIn: ['BP-02', 'BP-04'],
  },
  {
    id: 'var-apiTimeout',
    name: 'apiTimeout',
    defaultValue: '30000',
    overrides: {},
    type: 'plain',
    scope: 'workflow',
    sensitive: false,
    description: 'API 请求超时时间（毫秒），默认 30 秒。',
    updatedAt: '2026-06-19 16:45',
    updatedBy: 'QA_team',
    usedIn: ['BP-01', 'BP-02', 'BP-03', 'BP-04', 'BP-05', 'BP-06'],
  },
  {
    id: 'var-maxRetries',
    name: 'maxRetries',
    defaultValue: '3',
    overrides: {},
    type: 'plain',
    scope: 'workflow',
    sensitive: false,
    description: '失败步骤的最大重试次数，超出后标记流程失败。',
    updatedAt: '2026-06-16 11:00',
    updatedBy: 'QA_team',
    usedIn: ['BP-02', 'BP-05', 'BP-06'],
  },
  {
    id: 'var-dbReadOnly',
    name: 'dbReadOnlyToken',
    defaultValue: 'sk_ro_local_dev_token',
    overrides: {
      'env-test': 'sk_ro_test_3fA8zL2kQ9xM6wV',
      'env-staging': 'sk_ro_staging_4gB9yM3lR0nN7xW',
      'env-prod': 'sk_ro_prod_5hC0zN4mS1oO8yX',
    },
    type: 'secret',
    scope: 'environment',
    sensitive: true,
    description: '数据库只读访问令牌，用于验证数据写入后的持久化结果。',
    updatedAt: '2026-06-14 13:30',
    updatedBy: 'QA_team',
    usedIn: ['BP-04'],
  },
  {
    id: 'var-userDataset',
    name: 'testUsers',
    defaultValue: '{"admin":{"username":"admin","password":"***"},"guest":{"username":"guest","password":"***"}}',
    overrides: {},
    type: 'dataset',
    scope: 'environment',
    sensitive: true,
    description: '测试用户数据集，包含不同角色的登录凭证。',
    updatedAt: '2026-06-13 10:00',
    updatedBy: 'QA_team',
    usedIn: ['BP-01', 'BP-07'],
  },
  {
    id: 'var-pollInterval',
    name: 'pollIntervalMs',
    defaultValue: '2000',
    overrides: {},
    type: 'plain',
    scope: 'workflow',
    sensitive: false,
    description: '轮询间隔（毫秒），用于支付状态等异步场景。',
    updatedAt: '2026-06-18 15:20',
    updatedBy: 'QA_team',
    usedIn: ['BP-05'],
  },
];

// ─── Report Center: Test Plans ─────────────────────────────────

export const testPlans: TestPlan[] = [
  {
    id: 'plan-full',
    name: '全量回归',
    description: '运行全部 8 个业务流程，覆盖所有 Happy Path 和异常路径。',
    tagFilter: 'any',
    tags: ['全量'],
    workflowCount: 8,
  },
  {
    id: 'plan-smoke',
    name: '核心流程冒烟测试',
    description: '只运行标记为"核心流程"或"Happy Path"的关键路径，快速验证基本可用性。',
    tagFilter: 'any',
    tags: ['核心流程', 'Happy Path'],
    workflowCount: 2,
  },
  {
    id: 'plan-error-paths',
    name: '异常路径专项',
    description: '运行标记为"异常"的业务流程，验证错误处理、幂等保护和认证拦截。',
    tagFilter: 'any',
    tags: ['异常'],
    workflowCount: 3,
  },
  {
    id: 'plan-payment',
    name: '支付相关回归',
    description: '运行所有与支付相关的流程，包括正常支付、幂等保护和异步轮询。',
    tagFilter: 'any',
    tags: ['支付'],
    workflowCount: 3,
  },
];

// ─── Report Center: Runs (execution batches) ──────────────────
//
// Each Run aggregates results of multiple workflows executed
// together under a plan or tag selection.

export const initialRuns: RunMeta[] = [
  // ── Run 1: 全量回归 · 测试环境 (7/8 passed, 1 failed) ─────
  {
    id: 'run-001',
    runId: '#ST-20260623-001',
    name: '全量回归 · 测试环境',
    planId: 'plan-full',
    environment: '测试环境',
    trigger: 'manual',
    status: 'failed',
    totalWorkflows: 8,
    workflowsPassed: 7,
    workflowsFailed: 1,
    workflowsSkipped: 0,
    totalDurationMs: 31240,
    startedAt: '2026-06-23 09:12:05',
    finishedAt: '2026-06-23 09:12:36',
    selectedTags: ['全量'],
    gitCommit: 'refactor: 认证中间件升级',
    gitSha: 'c7e1a5d',
    runnerVersion: 'v1.8.3',
    traceId: '4f2c1e8b9d7e4a17',
    openapiVersion: 'openapi.yaml · v2.3.1',
    workflows: [
      {
        workflowId: 'wf-bp01',
        workflowName: '用户注册与认证',
        bpId: 'BP-01',
        status: 'passed',
        stepsPassed: 3,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 1672,
        steps: [
          {
            id: 'r1-bp01-s1',
            name: '创建用户',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 512,
            responseStatus: 201,
          },
          {
            id: 'r1-bp01-s2',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 320,
            responseStatus: 200,
          },
          {
            id: 'r1-bp01-s3',
            name: '验证身份',
            method: 'GET',
            path: '/api/auth/me',
            status: 'passed',
            durationMs: 840,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp02',
        workflowName: '创建订单并支付',
        bpId: 'BP-02',
        status: 'passed',
        stepsPassed: 5,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 18427,
        steps: [
          {
            id: 'r1-bp02-s1',
            name: '创建用户',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 5420,
            responseStatus: 201,
          },
          {
            id: 'r1-bp02-s2',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 2830,
            responseStatus: 200,
          },
          {
            id: 'r1-bp02-s3',
            name: '创建订单',
            method: 'POST',
            path: '/api/orders',
            status: 'passed',
            durationMs: 3980,
            responseStatus: 201,
          },
          {
            id: 'r1-bp02-s4',
            name: '支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 3420,
            responseStatus: 200,
          },
          {
            id: 'r1-bp02-s5',
            name: '验证状态',
            method: 'GET',
            path: '/api/orders/{orderId}',
            status: 'passed',
            durationMs: 2777,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp03',
        workflowName: '订单生命周期管理',
        bpId: 'BP-03',
        status: 'passed',
        stepsPassed: 3,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 2153,
        steps: [
          {
            id: 'r1-bp03-s1',
            name: '创建订单',
            method: 'POST',
            path: '/api/orders',
            status: 'passed',
            durationMs: 702,
            responseStatus: 201,
          },
          {
            id: 'r1-bp03-s2',
            name: '查询订单',
            method: 'GET',
            path: '/api/orders/{orderId}',
            status: 'passed',
            durationMs: 489,
            responseStatus: 200,
          },
          {
            id: 'r1-bp03-s3',
            name: '取消订单',
            method: 'DELETE',
            path: '/api/orders/{orderId}',
            status: 'passed',
            durationMs: 962,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp04',
        workflowName: '用户信息查询与更新',
        bpId: 'BP-04',
        status: 'passed',
        stepsPassed: 2,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 1230,
        steps: [
          {
            id: 'r1-bp04-s1',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 445,
            responseStatus: 200,
          },
          {
            id: 'r1-bp04-s2',
            name: '查询用户',
            method: 'GET',
            path: '/api/users/{userId}',
            status: 'passed',
            durationMs: 785,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp05',
        workflowName: '支付状态轮询',
        bpId: 'BP-05',
        status: 'passed',
        stepsPassed: 2,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 3240,
        steps: [
          {
            id: 'r1-bp05-s1',
            name: '发起支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 890,
            responseStatus: 200,
          },
          {
            id: 'r1-bp05-s2',
            name: '轮询状态',
            method: 'GET',
            path: '/api/orders/{orderId}',
            status: 'passed',
            durationMs: 2350,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp06',
        workflowName: '异常路径：重复支付保护',
        bpId: 'BP-06',
        status: 'passed',
        stepsPassed: 2,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 1437,
        steps: [
          {
            id: 'r1-bp06-s1',
            name: '首次支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 782,
            responseStatus: 200,
          },
          {
            id: 'r1-bp06-s2',
            name: '重复支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 655,
            responseStatus: 409,
          },
        ],
      },
      {
        workflowId: 'wf-bp07',
        workflowName: '异常路径：认证失败处理',
        bpId: 'BP-07',
        status: 'failed',
        stepsPassed: 0,
        stepsFailed: 1,
        stepsSkipped: 0,
        totalDurationMs: 523,
        steps: [
          {
            id: 'r1-bp07-s1',
            name: '错误凭证登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'failed',
            durationMs: 523,
            responseStatus: 200,
            requestEvidence:
              'POST /api/auth/login\nContent-Type: application/json\n\n{ "username": "invalid_user", "password": "wrong_pass" }',
            responseEvidence:
              'HTTP/1.1 200 OK\nContent-Type: application/json\n\n{ "code": 0, "data": { "accessToken": "sk_test_******" }, "message": "success" }',
            assertionFailure: '期望状态码 401，实际 200。认证中间件未拒绝无效凭证（安全回归）。',
          },
        ],
      },
      {
        workflowId: 'wf-bp08',
        workflowName: '异常路径：参数校验失败',
        bpId: 'BP-08',
        status: 'passed',
        stepsPassed: 1,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 558,
        steps: [
          {
            id: 'r1-bp08-s1',
            name: '缺失字段请求',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 558,
            responseStatus: 400,
          },
        ],
      },
    ],
  },

  // ── Run 2: 核心流程冒烟测试 · 测试环境 (all passed) ──────
  {
    id: 'run-002',
    runId: '#ST-20260623-002',
    name: '核心流程冒烟 · 测试环境',
    planId: 'plan-smoke',
    environment: '测试环境',
    trigger: 'ci',
    status: 'passed',
    totalWorkflows: 2,
    workflowsPassed: 2,
    workflowsFailed: 0,
    workflowsSkipped: 0,
    totalDurationMs: 4890,
    startedAt: '2026-06-23 08:30:00',
    finishedAt: '2026-06-23 08:30:05',
    selectedTags: ['核心流程', 'Happy Path'],
    gitCommit: 'fix: 支付网关超时重试',
    gitSha: 'b8e4d2f',
    runnerVersion: 'v1.8.3',
    traceId: 'a3d7f2c9e1b5d8a4',
    openapiVersion: 'openapi.yaml · v2.3.1',
    workflows: [
      {
        workflowId: 'wf-bp01',
        workflowName: '用户注册与认证',
        bpId: 'BP-01',
        status: 'passed',
        stepsPassed: 3,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 1520,
        steps: [
          {
            id: 'r2-bp01-s1',
            name: '创建用户',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 488,
            responseStatus: 201,
          },
          {
            id: 'r2-bp01-s2',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 295,
            responseStatus: 200,
          },
          {
            id: 'r2-bp01-s3',
            name: '验证身份',
            method: 'GET',
            path: '/api/auth/me',
            status: 'passed',
            durationMs: 737,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp02',
        workflowName: '创建订单并支付',
        bpId: 'BP-02',
        status: 'passed',
        stepsPassed: 5,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 3370,
        steps: [
          {
            id: 'r2-bp02-s1',
            name: '创建用户',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 610,
            responseStatus: 201,
          },
          {
            id: 'r2-bp02-s2',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 385,
            responseStatus: 200,
          },
          {
            id: 'r2-bp02-s3',
            name: '创建订单',
            method: 'POST',
            path: '/api/orders',
            status: 'passed',
            durationMs: 842,
            responseStatus: 201,
          },
          {
            id: 'r2-bp02-s4',
            name: '支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 989,
            responseStatus: 200,
          },
          {
            id: 'r2-bp02-s5',
            name: '验证状态',
            method: 'GET',
            path: '/api/orders/{orderId}',
            status: 'passed',
            durationMs: 544,
            responseStatus: 200,
          },
        ],
      },
    ],
  },

  // ── Run 3: 异常路径专项 · 测试环境 (2/3 passed) ──────────
  {
    id: 'run-003',
    runId: '#ST-20260622-003',
    name: '异常路径专项 · 测试环境',
    planId: 'plan-error-paths',
    environment: '测试环境',
    trigger: 'scheduled',
    status: 'failed',
    totalWorkflows: 3,
    workflowsPassed: 2,
    workflowsFailed: 1,
    workflowsSkipped: 0,
    totalDurationMs: 4215,
    startedAt: '2026-06-22 22:00:00',
    finishedAt: '2026-06-22 22:00:04',
    selectedTags: ['异常'],
    gitCommit: 'fix: 幂等性校验增强',
    gitSha: 'f3b9d1e',
    runnerVersion: 'v1.8.2',
    traceId: '9a1c5e3b7f2d4a8c',
    openapiVersion: 'openapi.yaml · v2.3.0',
    workflows: [
      {
        workflowId: 'wf-bp06',
        workflowName: '异常路径：重复支付保护',
        bpId: 'BP-06',
        status: 'passed',
        stepsPassed: 2,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 1320,
        steps: [
          {
            id: 'r3-bp06-s1',
            name: '首次支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 745,
            responseStatus: 200,
          },
          {
            id: 'r3-bp06-s2',
            name: '重复支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 575,
            responseStatus: 409,
          },
        ],
      },
      {
        workflowId: 'wf-bp07',
        workflowName: '异常路径：认证失败处理',
        bpId: 'BP-07',
        status: 'failed',
        stepsPassed: 0,
        stepsFailed: 1,
        stepsSkipped: 0,
        totalDurationMs: 480,
        steps: [
          {
            id: 'r3-bp07-s1',
            name: '错误凭证登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'failed',
            durationMs: 480,
            responseStatus: 200,
            requestEvidence:
              'POST /api/auth/login\nContent-Type: application/json\n\n{ "username": "attacker", "password": "guess" }',
            responseEvidence:
              'HTTP/1.1 200 OK\nContent-Type: application/json\n\n{ "code": 0, "data": { "accessToken": "sk_test_******" }, "message": "success" }',
            assertionFailure: '期望状态码 401，实际 200。无效凭证未被拦截，存在安全风险。',
          },
        ],
      },
      {
        workflowId: 'wf-bp08',
        workflowName: '异常路径：参数校验失败',
        bpId: 'BP-08',
        status: 'passed',
        stepsPassed: 1,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 415,
        steps: [
          {
            id: 'r3-bp08-s1',
            name: '缺失字段请求',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 415,
            responseStatus: 400,
          },
        ],
      },
    ],
  },

  // ── Run 4: 全量回归 · 预发布环境 (all passed) ────────────
  {
    id: 'run-004',
    runId: '#ST-20260622-004',
    name: '全量回归 · 预发布环境',
    planId: 'plan-full',
    environment: '预发布环境',
    trigger: 'scheduled',
    status: 'passed',
    totalWorkflows: 8,
    workflowsPassed: 8,
    workflowsFailed: 0,
    workflowsSkipped: 0,
    totalDurationMs: 28350,
    startedAt: '2026-06-22 16:00:00',
    finishedAt: '2026-06-22 16:00:28',
    selectedTags: ['全量'],
    gitCommit: 'feat: 订单状态机完善',
    gitSha: 'f7c3b1e',
    runnerVersion: 'v1.8.2',
    traceId: '4d1f7b3a9c5e2d8f',
    openapiVersion: 'openapi.yaml · v2.3.0',
    workflows: [
      {
        workflowId: 'wf-bp01',
        workflowName: '用户注册与认证',
        bpId: 'BP-01',
        status: 'passed',
        stepsPassed: 3,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 1892,
        steps: [
          {
            id: 'r4-bp01-s1',
            name: '创建用户',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 612,
            responseStatus: 201,
          },
          {
            id: 'r4-bp01-s2',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 410,
            responseStatus: 200,
          },
          {
            id: 'r4-bp01-s3',
            name: '验证身份',
            method: 'GET',
            path: '/api/auth/me',
            status: 'passed',
            durationMs: 870,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp02',
        workflowName: '创建订单并支付',
        bpId: 'BP-02',
        status: 'passed',
        stepsPassed: 5,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 5620,
        steps: [
          {
            id: 'r4-bp02-s1',
            name: '创建用户',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 1320,
            responseStatus: 201,
          },
          {
            id: 'r4-bp02-s2',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 980,
            responseStatus: 200,
          },
          {
            id: 'r4-bp02-s3',
            name: '创建订单',
            method: 'POST',
            path: '/api/orders',
            status: 'passed',
            durationMs: 1200,
            responseStatus: 201,
          },
          {
            id: 'r4-bp02-s4',
            name: '支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 1100,
            responseStatus: 200,
          },
          {
            id: 'r4-bp02-s5',
            name: '验证状态',
            method: 'GET',
            path: '/api/orders/{orderId}',
            status: 'passed',
            durationMs: 1020,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp03',
        workflowName: '订单生命周期管理',
        bpId: 'BP-03',
        status: 'passed',
        stepsPassed: 3,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 2310,
        steps: [
          {
            id: 'r4-bp03-s1',
            name: '创建订单',
            method: 'POST',
            path: '/api/orders',
            status: 'passed',
            durationMs: 756,
            responseStatus: 201,
          },
          {
            id: 'r4-bp03-s2',
            name: '查询订单',
            method: 'GET',
            path: '/api/orders/{orderId}',
            status: 'passed',
            durationMs: 534,
            responseStatus: 200,
          },
          {
            id: 'r4-bp03-s3',
            name: '取消订单',
            method: 'DELETE',
            path: '/api/orders/{orderId}',
            status: 'passed',
            durationMs: 1020,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp04',
        workflowName: '用户信息查询与更新',
        bpId: 'BP-04',
        status: 'passed',
        stepsPassed: 2,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 980,
        steps: [
          {
            id: 'r4-bp04-s1',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 380,
            responseStatus: 200,
          },
          {
            id: 'r4-bp04-s2',
            name: '查询用户',
            method: 'GET',
            path: '/api/users/{userId}',
            status: 'passed',
            durationMs: 600,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp05',
        workflowName: '支付状态轮询',
        bpId: 'BP-05',
        status: 'passed',
        stepsPassed: 2,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 8940,
        steps: [
          {
            id: 'r4-bp05-s1',
            name: '发起支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 940,
            responseStatus: 200,
          },
          {
            id: 'r4-bp05-s2',
            name: '轮询状态',
            method: 'GET',
            path: '/api/orders/{orderId}',
            status: 'passed',
            durationMs: 8000,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp06',
        workflowName: '异常路径：重复支付保护',
        bpId: 'BP-06',
        status: 'passed',
        stepsPassed: 2,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 1120,
        steps: [
          {
            id: 'r4-bp06-s1',
            name: '首次支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 630,
            responseStatus: 200,
          },
          {
            id: 'r4-bp06-s2',
            name: '重复支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 490,
            responseStatus: 409,
          },
        ],
      },
      {
        workflowId: 'wf-bp07',
        workflowName: '异常路径：认证失败处理',
        bpId: 'BP-07',
        status: 'passed',
        stepsPassed: 1,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 420,
        steps: [
          {
            id: 'r4-bp07-s1',
            name: '错误凭证登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 420,
            responseStatus: 401,
          },
        ],
      },
      {
        workflowId: 'wf-bp08',
        workflowName: '异常路径：参数校验失败',
        bpId: 'BP-08',
        status: 'passed',
        stepsPassed: 1,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 480,
        steps: [
          {
            id: 'r4-bp08-s1',
            name: '缺失字段请求',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 480,
            responseStatus: 400,
          },
        ],
      },
    ],
  },

  // ── Run 5: 支付相关回归 · 测试环境 (2/3, 1 inconclusive) ──
  {
    id: 'run-005',
    runId: '#ST-20260622-005',
    name: '支付相关回归 · 测试环境',
    planId: 'plan-payment',
    environment: '测试环境',
    trigger: 'webhook',
    status: 'inconclusive',
    totalWorkflows: 3,
    workflowsPassed: 2,
    workflowsFailed: 0,
    workflowsSkipped: 1,
    totalDurationMs: 16180,
    startedAt: '2026-06-22 14:05:33',
    finishedAt: '2026-06-22 14:05:49',
    selectedTags: ['支付'],
    gitCommit: 'feat: 异步支付通知',
    gitSha: 'a8c2e6d',
    runnerVersion: 'v1.8.2',
    traceId: '2d7b1f5a9c3e6b8d',
    openapiVersion: 'openapi.yaml · v2.3.0',
    workflows: [
      {
        workflowId: 'wf-bp02',
        workflowName: '创建订单并支付',
        bpId: 'BP-02',
        status: 'passed',
        stepsPassed: 5,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 3591,
        steps: [
          {
            id: 'r5-bp02-s1',
            name: '创建用户',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 610,
            responseStatus: 201,
          },
          {
            id: 'r5-bp02-s2',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 385,
            responseStatus: 200,
          },
          {
            id: 'r5-bp02-s3',
            name: '创建订单',
            method: 'POST',
            path: '/api/orders',
            status: 'passed',
            durationMs: 842,
            responseStatus: 201,
          },
          {
            id: 'r5-bp02-s4',
            name: '支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 1210,
            responseStatus: 200,
          },
          {
            id: 'r5-bp02-s5',
            name: '验证状态',
            method: 'GET',
            path: '/api/orders/{orderId}',
            status: 'passed',
            durationMs: 544,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp05',
        workflowName: '支付状态轮询',
        bpId: 'BP-05',
        status: 'skipped',
        stepsPassed: 1,
        stepsFailed: 0,
        stepsSkipped: 1,
        totalDurationMs: 12450,
        steps: [
          {
            id: 'r5-bp05-s1',
            name: '发起支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 890,
            responseStatus: 200,
          },
          {
            id: 'r5-bp05-s2',
            name: '轮询状态',
            method: 'GET',
            path: '/api/orders/{orderId}',
            status: 'skipped',
            durationMs: 11560,
            responseStatus: 0,
            assertionFailure: '轮询超时：在 10 秒内未等到订单状态变更为"已支付"，步骤被跳过。',
          },
        ],
      },
      {
        workflowId: 'wf-bp06',
        workflowName: '异常路径：重复支付保护',
        bpId: 'BP-06',
        status: 'passed',
        stepsPassed: 2,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 139,
        steps: [
          {
            id: 'r5-bp06-s1',
            name: '首次支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 82,
            responseStatus: 200,
          },
          {
            id: 'r5-bp06-s2',
            name: '重复支付',
            method: 'POST',
            path: '/api/payments',
            status: 'passed',
            durationMs: 57,
            responseStatus: 409,
          },
        ],
      },
    ],
  },

  // ── Run 6: 核心流程冒烟 · 预发布环境 (1/2, 1 infra-error) ──
  {
    id: 'run-006',
    runId: '#ST-20260621-006',
    name: '核心流程冒烟 · 预发布环境',
    planId: 'plan-smoke',
    environment: '预发布环境',
    trigger: 'manual',
    status: 'infra-error',
    totalWorkflows: 2,
    workflowsPassed: 1,
    workflowsFailed: 0,
    workflowsSkipped: 1,
    totalDurationMs: 32132,
    startedAt: '2026-06-21 12:10:15',
    finishedAt: '2026-06-21 12:10:47',
    selectedTags: ['核心流程', 'Happy Path'],
    gitCommit: 'chore: CI 流水线配置更新',
    gitSha: 'e1a5c9d',
    runnerVersion: 'v1.8.1',
    traceId: '6c0e4a8f2d1b7e5a',
    openapiVersion: 'openapi.yaml · v2.2.0',
    workflows: [
      {
        workflowId: 'wf-bp01',
        workflowName: '用户注册与认证',
        bpId: 'BP-01',
        status: 'passed',
        stepsPassed: 3,
        stepsFailed: 0,
        stepsSkipped: 0,
        totalDurationMs: 1612,
        steps: [
          {
            id: 'r6-bp01-s1',
            name: '创建用户',
            method: 'POST',
            path: '/api/users',
            status: 'passed',
            durationMs: 498,
            responseStatus: 201,
          },
          {
            id: 'r6-bp01-s2',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'passed',
            durationMs: 356,
            responseStatus: 200,
          },
          {
            id: 'r6-bp01-s3',
            name: '验证身份',
            method: 'GET',
            path: '/api/auth/me',
            status: 'passed',
            durationMs: 758,
            responseStatus: 200,
          },
        ],
      },
      {
        workflowId: 'wf-bp02',
        workflowName: '创建订单并支付',
        bpId: 'BP-02',
        status: 'error',
        stepsPassed: 0,
        stepsFailed: 0,
        stepsSkipped: 5,
        totalDurationMs: 30520,
        steps: [
          {
            id: 'r6-bp02-s1',
            name: '创建用户',
            method: 'POST',
            path: '/api/users',
            status: 'skipped',
            durationMs: 30520,
            responseStatus: 0,
            assertionFailure:
              'Runner 进程异常退出 (OOM)，未能完成任何步骤。请检查 Runner 资源配额。',
          },
          {
            id: 'r6-bp02-s2',
            name: '登录',
            method: 'POST',
            path: '/api/auth/login',
            status: 'skipped',
            durationMs: 0,
            responseStatus: 0,
          },
          {
            id: 'r6-bp02-s3',
            name: '创建订单',
            method: 'POST',
            path: '/api/orders',
            status: 'skipped',
            durationMs: 0,
            responseStatus: 0,
          },
          {
            id: 'r6-bp02-s4',
            name: '支付',
            method: 'POST',
            path: '/api/payments',
            status: 'skipped',
            durationMs: 0,
            responseStatus: 0,
          },
          {
            id: 'r6-bp02-s5',
            name: '验证状态',
            method: 'GET',
            path: '/api/orders/{orderId}',
            status: 'skipped',
            durationMs: 0,
            responseStatus: 0,
          },
        ],
      },
    ],
  },
];
